# Generated by Django 5.2.14 on 2026-06-01 03:35

import bookmanagement.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTypes',
            fields=[
                ('typeid', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='类型编号')),
                ('typename', models.CharField(default='', max_length=8, verbose_name='类型名称')),
            ],
            options={
                'db_table': 'booktypes',
            },
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('pubid', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='出版社编号')),
                ('pubname', models.CharField(default='', max_length=20, verbose_name='出版社名称')),
                ('pubaddr', models.CharField(max_length=50, null=True, verbose_name='出版社地址')),
            ],
            options={
                'db_table': 'publishers',
            },
        ),
        migrations.CreateModel(
            name='UserTypes',
            fields=[
                ('typeid', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='类型编号')),
                ('typename', models.CharField(default='', max_length=8, verbose_name='类型名称')),
            ],
            options={
                'db_table': 'usertypes',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bookid', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='图书编号')),
                ('bookname', models.CharField(max_length=50, verbose_name='图书名称')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('publishdate', models.DateField(null=True, verbose_name='出版日期')),
                ('ISBN', models.CharField(max_length=20, verbose_name='ISBN')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='价格')),
                ('desc', models.CharField(default='', max_length=200, null=True, verbose_name='简介')),
                ('booktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmanagement.booktypes', verbose_name='图书类别')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmanagement.publishers', verbose_name='出版社')),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=2, verbose_name='性别')),
                ('enrolldate', models.IntegerField(default=bookmanagement.models.current_year, verbose_name='入学时间')),
                ('groups', models.ManyToManyField(blank=True, related_name='book_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='book_users', to='auth.permission', verbose_name='user permissions')),
                ('usertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmanagement.usertypes', verbose_name='用户类型')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Borrows',
            fields=[
                ('borrowid', models.AutoField(primary_key=True, serialize=False, verbose_name='借阅编号')),
                ('borrowdate', models.DateField(auto_now_add=True, verbose_name='出借日期')),
                ('returndate', models.DateField(blank=True, null=True, verbose_name='归还日期')),
                ('pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='费用')),
                ('returntype', models.IntegerField(choices=[(0, '未归还'), (1, '已归还'), (2, '逾期归还'), (3, '丢失赔偿')], default=0, verbose_name='归还类型')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmanagement.books', verbose_name='图书')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmanagement.users', verbose_name='用户名')),
            ],
            options={
                'db_table': 'borrows',
            },
        ),
    ]
